sconfig:
  'time_limit': '0:01:00'
  'ntasks': 1
  'nodes': 1
  'mem_per_cpu': '8G'
  'cpus-per-task': 12
  'job-name': 'TDHF_test'
  'A': 'ptg'

modules:
  - powertools
  - intel/2023a
  - FFTW

tdhf_in:
  'AL': 40
  'ZL': 20
  'alpha': 0.0
  'beta': 0.0
  'gamma': 0.0
  